// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaVotoElectronico.Api.Migrations
{
    [DbContext(typeof(SistemaVotoElectronicoApiContext))]
    [Migration("20260205153219_PgV01")]
    partial class PgV01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVoto.Modelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListaPoliticaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanGobiernoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListaPoliticaId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventoElectoralId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoElectoralId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.EventoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventosElectorales");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.ListaPolitica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Eslogan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventoElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventoElectoralId");

                    b.ToTable("ListasPoliticas");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.ResultadoEleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoElectoralId")
                        .HasColumnType("integer");

                    b.Property<int>("ListaPoliticaId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalVotos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoElectoralId");

                    b.HasIndex("ListaPoliticaId");

                    b.ToTable("ResultadosElecciones");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RolUsuarios");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenVotacion")
                        .HasColumnType("text");

                    b.Property<bool>("YaVoto")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("RolUsuarioId");

                    b.HasIndex("TokenVotacion")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoElectoralId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashSeguridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ListaPoliticaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoElectoralId");

                    b.HasIndex("ListaPoliticaId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Candidato", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.ListaPolitica", "ListaPolitica")
                        .WithMany()
                        .HasForeignKey("ListaPoliticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaPolitica");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Certificado", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.EventoElectoral", "EventoElectoral")
                        .WithMany()
                        .HasForeignKey("EventoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoElectoral");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.ListaPolitica", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.EventoElectoral", "EventoElectoral")
                        .WithMany()
                        .HasForeignKey("EventoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoElectoral");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.ResultadoEleccion", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.EventoElectoral", "EventoElectoral")
                        .WithMany()
                        .HasForeignKey("EventoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.ListaPolitica", "ListaPolitica")
                        .WithMany()
                        .HasForeignKey("ListaPoliticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoElectoral");

                    b.Navigation("ListaPolitica");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Usuario", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.RolUsuario", "RolUsuario")
                        .WithMany()
                        .HasForeignKey("RolUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolUsuario");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Voto", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.EventoElectoral", "EventoElectoral")
                        .WithMany()
                        .HasForeignKey("EventoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.ListaPolitica", "ListaPolitica")
                        .WithMany()
                        .HasForeignKey("ListaPoliticaId");

                    b.Navigation("EventoElectoral");

                    b.Navigation("ListaPolitica");
                });
#pragma warning restore 612, 618
        }
    }
}
